
  create table "public"."gym_performances" (
    "id" smallint generated by default as identity not null,
    "group_name" text not null,
    "round_name" text not null,
    "start_at" timestamp with time zone not null,
    "end_at" timestamp with time zone not null,
    "capacity" smallint not null,
    "year" smallint not null
      );


alter table "public"."gym_performances" enable row level security;


  create table "public"."gym_tickets" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "performance_id" smallint not null
      );


alter table "public"."gym_tickets" enable row level security;

CREATE UNIQUE INDEX gym_performances_pkey ON public.gym_performances USING btree (id);

CREATE INDEX gym_tickets_performance_id_idx ON public.gym_tickets USING btree (performance_id);

CREATE UNIQUE INDEX gym_tickets_pkey ON public.gym_tickets USING btree (id);

alter table "public"."gym_performances" add constraint "gym_performances_pkey" PRIMARY KEY using index "gym_performances_pkey";

alter table "public"."gym_tickets" add constraint "gym_tickets_pkey" PRIMARY KEY using index "gym_tickets_pkey";

alter table "public"."gym_tickets" add constraint "gym_tickets_id_fkey" FOREIGN KEY (id) REFERENCES public.tickets(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."gym_tickets" validate constraint "gym_tickets_id_fkey";

alter table "public"."gym_tickets" add constraint "gym_tickets_performance_id_fkey" FOREIGN KEY (performance_id) REFERENCES public.gym_performances(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."gym_tickets" validate constraint "gym_tickets_performance_id_fkey";

grant delete on table "public"."gym_performances" to "anon";

grant insert on table "public"."gym_performances" to "anon";

grant references on table "public"."gym_performances" to "anon";

grant select on table "public"."gym_performances" to "anon";

grant trigger on table "public"."gym_performances" to "anon";

grant truncate on table "public"."gym_performances" to "anon";

grant update on table "public"."gym_performances" to "anon";

grant delete on table "public"."gym_performances" to "authenticated";

grant insert on table "public"."gym_performances" to "authenticated";

grant references on table "public"."gym_performances" to "authenticated";

grant select on table "public"."gym_performances" to "authenticated";

grant trigger on table "public"."gym_performances" to "authenticated";

grant truncate on table "public"."gym_performances" to "authenticated";

grant update on table "public"."gym_performances" to "authenticated";

grant delete on table "public"."gym_performances" to "service_role";

grant insert on table "public"."gym_performances" to "service_role";

grant references on table "public"."gym_performances" to "service_role";

grant select on table "public"."gym_performances" to "service_role";

grant trigger on table "public"."gym_performances" to "service_role";

grant truncate on table "public"."gym_performances" to "service_role";

grant update on table "public"."gym_performances" to "service_role";

grant delete on table "public"."gym_tickets" to "anon";

grant insert on table "public"."gym_tickets" to "anon";

grant references on table "public"."gym_tickets" to "anon";

grant select on table "public"."gym_tickets" to "anon";

grant trigger on table "public"."gym_tickets" to "anon";

grant truncate on table "public"."gym_tickets" to "anon";

grant update on table "public"."gym_tickets" to "anon";

grant delete on table "public"."gym_tickets" to "authenticated";

grant insert on table "public"."gym_tickets" to "authenticated";

grant references on table "public"."gym_tickets" to "authenticated";

grant select on table "public"."gym_tickets" to "authenticated";

grant trigger on table "public"."gym_tickets" to "authenticated";

grant truncate on table "public"."gym_tickets" to "authenticated";

grant update on table "public"."gym_tickets" to "authenticated";

grant delete on table "public"."gym_tickets" to "service_role";

grant insert on table "public"."gym_tickets" to "service_role";

grant references on table "public"."gym_tickets" to "service_role";

grant select on table "public"."gym_tickets" to "service_role";

grant trigger on table "public"."gym_tickets" to "service_role";

grant truncate on table "public"."gym_tickets" to "service_role";

grant update on table "public"."gym_tickets" to "service_role";


  create policy "Enable read access for all users"
  on "public"."gym_performances"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."gym_tickets"
  as permissive
  for select
  to public
using (true);



