alter table "public"."performances" drop constraint "performances_pkey";

drop index if exists "public"."performances_pkey";

alter table "public"."performances" add column "id" smallint generated by default as identity not null;

alter table "public"."performances_schedule" drop constraint if exists "performances_schedule_pkey";

drop index if exists "public"."performances_schedule_pkey";

alter table "public"."performances_schedule" drop column "id";

alter table "public"."performances_schedule" add column "id" smallint generated by default as identity not null;

CREATE UNIQUE INDEX performances_pkey ON public.performances USING btree (id);

CREATE UNIQUE INDEX performances_schedule_pkey ON public.performances_schedule USING btree (id);

alter table "public"."performances" add constraint "performances_pkey" PRIMARY KEY using index "performances_pkey";

alter table "public"."performances_schedule" add constraint "performances_schedule_pkey" PRIMARY KEY using index "performances_schedule_pkey";
