drop policy "Enable read access for all users" on "public"."performances";

drop policy "Enable read access for all users" on "public"."performances_schedule";

revoke delete on table "public"."performances" from "anon";

revoke insert on table "public"."performances" from "anon";

revoke references on table "public"."performances" from "anon";

revoke select on table "public"."performances" from "anon";

revoke trigger on table "public"."performances" from "anon";

revoke truncate on table "public"."performances" from "anon";

revoke update on table "public"."performances" from "anon";

revoke delete on table "public"."performances" from "authenticated";

revoke insert on table "public"."performances" from "authenticated";

revoke references on table "public"."performances" from "authenticated";

revoke select on table "public"."performances" from "authenticated";

revoke trigger on table "public"."performances" from "authenticated";

revoke truncate on table "public"."performances" from "authenticated";

revoke update on table "public"."performances" from "authenticated";

revoke delete on table "public"."performances" from "service_role";

revoke insert on table "public"."performances" from "service_role";

revoke references on table "public"."performances" from "service_role";

revoke select on table "public"."performances" from "service_role";

revoke trigger on table "public"."performances" from "service_role";

revoke truncate on table "public"."performances" from "service_role";

revoke update on table "public"."performances" from "service_role";

revoke delete on table "public"."performances_schedule" from "anon";

revoke insert on table "public"."performances_schedule" from "anon";

revoke references on table "public"."performances_schedule" from "anon";

revoke select on table "public"."performances_schedule" from "anon";

revoke trigger on table "public"."performances_schedule" from "anon";

revoke truncate on table "public"."performances_schedule" from "anon";

revoke update on table "public"."performances_schedule" from "anon";

revoke delete on table "public"."performances_schedule" from "authenticated";

revoke insert on table "public"."performances_schedule" from "authenticated";

revoke references on table "public"."performances_schedule" from "authenticated";

revoke select on table "public"."performances_schedule" from "authenticated";

revoke trigger on table "public"."performances_schedule" from "authenticated";

revoke truncate on table "public"."performances_schedule" from "authenticated";

revoke update on table "public"."performances_schedule" from "authenticated";

revoke delete on table "public"."performances_schedule" from "service_role";

revoke insert on table "public"."performances_schedule" from "service_role";

revoke references on table "public"."performances_schedule" from "service_role";

revoke select on table "public"."performances_schedule" from "service_role";

revoke trigger on table "public"."performances_schedule" from "service_role";

revoke truncate on table "public"."performances_schedule" from "service_role";

revoke update on table "public"."performances_schedule" from "service_role";

alter table "public"."performances" drop constraint "performances_class_name_key";

alter table "public"."ticket_types" drop constraint "ticket_types_name_key";

alter table "public"."tickets" drop constraint "tickets_performance_id_fkey";

alter table "public"."tickets" drop constraint "tickets_round_number_fkey";

alter table "public"."rehearsals" drop constraint "rehearsals_class_id_fkey";

alter table "public"."performances" drop constraint "performances_pkey";

alter table "public"."performances_schedule" drop constraint "performances_schedule_pkey";

drop index if exists "public"."ticket_types_name_key";

drop index if exists "public"."performances_class_name_key";

drop index if exists "public"."performances_pkey";

drop index if exists "public"."performances_schedule_pkey";

drop table "public"."performances";

drop table "public"."performances_schedule";


  create table "public"."class_performances" (
    "year" smallint,
    "class_name" text,
    "title" text,
    "description" text,
    "created_at" timestamp with time zone not null default now(),
    "junior_capacity" smallint default '10'::smallint,
    "total_capacity" smallint default '50'::smallint,
    "id" smallint generated by default as identity not null
      );


alter table "public"."class_performances" enable row level security;


  create table "public"."class_performances_schedule" (
    "created_at" timestamp with time zone not null default now(),
    "start_at" timestamp with time zone not null,
    "id" smallint generated by default as identity not null,
    "is_active" boolean not null default true,
    "round_name" text not null
      );


alter table "public"."class_performances_schedule" enable row level security;


  create table "public"."class_tickets" (
    "id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "class_id" smallint not null,
    "round_id" smallint not null
      );


alter table "public"."class_tickets" enable row level security;

alter table "public"."relationships" add column "is_accepting" boolean not null default true;

alter table "public"."ticket_types" add column "type" text not null;

alter table "public"."ticket_types" alter column "name" drop not null;

alter table "public"."tickets" drop column "performance_id";

alter table "public"."tickets" drop column "round_number";

alter table "public"."tickets" add column "signature" text not null;

CREATE UNIQUE INDEX class_tickets_pkey ON public.class_tickets USING btree (id);

CREATE UNIQUE INDEX performances_class_name_key ON public.class_performances USING btree (class_name);

CREATE UNIQUE INDEX performances_pkey ON public.class_performances USING btree (id);

CREATE UNIQUE INDEX performances_schedule_pkey ON public.class_performances_schedule USING btree (id);

alter table "public"."class_performances" add constraint "performances_pkey" PRIMARY KEY using index "performances_pkey";

alter table "public"."class_performances_schedule" add constraint "performances_schedule_pkey" PRIMARY KEY using index "performances_schedule_pkey";

alter table "public"."class_tickets" add constraint "class_tickets_pkey" PRIMARY KEY using index "class_tickets_pkey";

alter table "public"."class_performances" add constraint "performances_class_name_key" UNIQUE using index "performances_class_name_key";

alter table "public"."class_tickets" add constraint "class_tickets_class_id_fkey" FOREIGN KEY (class_id) REFERENCES public.class_performances(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."class_tickets" validate constraint "class_tickets_class_id_fkey";

alter table "public"."class_tickets" add constraint "class_tickets_id_fkey" FOREIGN KEY (id) REFERENCES public.tickets(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."class_tickets" validate constraint "class_tickets_id_fkey";

alter table "public"."class_tickets" add constraint "class_tickets_round_id_fkey" FOREIGN KEY (round_id) REFERENCES public.class_performances_schedule(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."class_tickets" validate constraint "class_tickets_round_id_fkey";

alter table "public"."rehearsals" add constraint "rehearsals_class_id_fkey" FOREIGN KEY (class_id) REFERENCES public.class_performances(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."rehearsals" validate constraint "rehearsals_class_id_fkey";

grant delete on table "public"."class_performances" to "anon";

grant insert on table "public"."class_performances" to "anon";

grant references on table "public"."class_performances" to "anon";

grant select on table "public"."class_performances" to "anon";

grant trigger on table "public"."class_performances" to "anon";

grant truncate on table "public"."class_performances" to "anon";

grant update on table "public"."class_performances" to "anon";

grant delete on table "public"."class_performances" to "authenticated";

grant insert on table "public"."class_performances" to "authenticated";

grant references on table "public"."class_performances" to "authenticated";

grant select on table "public"."class_performances" to "authenticated";

grant trigger on table "public"."class_performances" to "authenticated";

grant truncate on table "public"."class_performances" to "authenticated";

grant update on table "public"."class_performances" to "authenticated";

grant delete on table "public"."class_performances" to "service_role";

grant insert on table "public"."class_performances" to "service_role";

grant references on table "public"."class_performances" to "service_role";

grant select on table "public"."class_performances" to "service_role";

grant trigger on table "public"."class_performances" to "service_role";

grant truncate on table "public"."class_performances" to "service_role";

grant update on table "public"."class_performances" to "service_role";

grant delete on table "public"."class_performances_schedule" to "anon";

grant insert on table "public"."class_performances_schedule" to "anon";

grant references on table "public"."class_performances_schedule" to "anon";

grant select on table "public"."class_performances_schedule" to "anon";

grant trigger on table "public"."class_performances_schedule" to "anon";

grant truncate on table "public"."class_performances_schedule" to "anon";

grant update on table "public"."class_performances_schedule" to "anon";

grant delete on table "public"."class_performances_schedule" to "authenticated";

grant insert on table "public"."class_performances_schedule" to "authenticated";

grant references on table "public"."class_performances_schedule" to "authenticated";

grant select on table "public"."class_performances_schedule" to "authenticated";

grant trigger on table "public"."class_performances_schedule" to "authenticated";

grant truncate on table "public"."class_performances_schedule" to "authenticated";

grant update on table "public"."class_performances_schedule" to "authenticated";

grant delete on table "public"."class_performances_schedule" to "service_role";

grant insert on table "public"."class_performances_schedule" to "service_role";

grant references on table "public"."class_performances_schedule" to "service_role";

grant select on table "public"."class_performances_schedule" to "service_role";

grant trigger on table "public"."class_performances_schedule" to "service_role";

grant truncate on table "public"."class_performances_schedule" to "service_role";

grant update on table "public"."class_performances_schedule" to "service_role";

grant delete on table "public"."class_tickets" to "anon";

grant insert on table "public"."class_tickets" to "anon";

grant references on table "public"."class_tickets" to "anon";

grant select on table "public"."class_tickets" to "anon";

grant trigger on table "public"."class_tickets" to "anon";

grant truncate on table "public"."class_tickets" to "anon";

grant update on table "public"."class_tickets" to "anon";

grant delete on table "public"."class_tickets" to "authenticated";

grant insert on table "public"."class_tickets" to "authenticated";

grant references on table "public"."class_tickets" to "authenticated";

grant select on table "public"."class_tickets" to "authenticated";

grant trigger on table "public"."class_tickets" to "authenticated";

grant truncate on table "public"."class_tickets" to "authenticated";

grant update on table "public"."class_tickets" to "authenticated";

grant delete on table "public"."class_tickets" to "postgres";

grant insert on table "public"."class_tickets" to "postgres";

grant references on table "public"."class_tickets" to "postgres";

grant select on table "public"."class_tickets" to "postgres";

grant trigger on table "public"."class_tickets" to "postgres";

grant truncate on table "public"."class_tickets" to "postgres";

grant update on table "public"."class_tickets" to "postgres";

grant delete on table "public"."class_tickets" to "service_role";

grant insert on table "public"."class_tickets" to "service_role";

grant references on table "public"."class_tickets" to "service_role";

grant select on table "public"."class_tickets" to "service_role";

grant trigger on table "public"."class_tickets" to "service_role";

grant truncate on table "public"."class_tickets" to "service_role";

grant update on table "public"."class_tickets" to "service_role";


  create policy "Enable read access for all users"
  on "public"."class_performances"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."class_performances_schedule"
  as permissive
  for select
  to public
using (true);



