alter table "public"."performances" drop constraint "performances_pkey";

drop index if exists "public"."performances_pkey";


  create table "public"."performances_schedule" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "round_number" smallint not null,
    "date_name" text not null,
    "start_at" timestamp with time zone not null
      );


alter table "public"."performances_schedule" enable row level security;


  create table "public"."relationships" (
    "id" smallint generated by default as identity not null,
    "name" text
      );


alter table "public"."relationships" enable row level security;


  create table "public"."ticket_types" (
    "id" smallint generated by default as identity not null,
    "name" text not null
      );


alter table "public"."ticket_types" enable row level security;


  create table "public"."tickets" (
    "id" uuid not null default gen_random_uuid(),
    "code" text not null,
    "performance_id" smallint not null,
    "round_number" smallint not null,
    "ticket_type" text not null,
    "status" text not null default 'active'::text,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "relationship" smallint not null
      );


alter table "public"."tickets" enable row level security;

alter table "public"."configs" add column "show_length" smallint not null default '60'::smallint;

alter table "public"."configs" add column "shows_per_day" smallint not null default '4'::smallint;

alter table "public"."performances" drop column "capacity_junior";

alter table "public"."performances" drop column "capacity_total";

alter table "public"."performances" drop column "end_at";

alter table "public"."performances" drop column "id";

alter table "public"."performances" drop column "start_at";

alter table "public"."performances" add column "class_id" smallint generated by default as identity not null;

alter table "public"."performances" add column "junior_capacity" smallint default '10'::smallint;

alter table "public"."performances" add column "junior_remaining" smallint default '10'::smallint;

alter table "public"."performances" add column "total_capacity" smallint default '50'::smallint;

alter table "public"."performances" add column "total_remaining" smallint default '50'::smallint;

alter table "public"."performances" alter column "class_name" drop not null;

alter table "public"."performances" alter column "created_at" set not null;

alter table "public"."performances" alter column "title" drop not null;

alter table "public"."performances" alter column "year" drop not null;

alter table "public"."performances" alter column "year" set data type smallint using "year"::smallint;

CREATE UNIQUE INDEX "Relationships_pkey" ON public.relationships USING btree (id);

CREATE UNIQUE INDEX performances_class_id_key ON public.performances USING btree (class_id);

CREATE UNIQUE INDEX performances_class_name_key ON public.performances USING btree (class_name);

CREATE UNIQUE INDEX performances_schedule_pkey ON public.performances_schedule USING btree (id);

CREATE UNIQUE INDEX performances_schedule_round_number_key ON public.performances_schedule USING btree (round_number);

CREATE UNIQUE INDEX ticket_types_name_key ON public.ticket_types USING btree (name);

CREATE UNIQUE INDEX ticket_types_pkey ON public.ticket_types USING btree (id);

CREATE UNIQUE INDEX tickets_code_key ON public.tickets USING btree (code);

CREATE UNIQUE INDEX tickets_pkey ON public.tickets USING btree (id);

CREATE UNIQUE INDEX performances_pkey ON public.performances USING btree (class_id);

alter table "public"."performances_schedule" add constraint "performances_schedule_pkey" PRIMARY KEY using index "performances_schedule_pkey";

alter table "public"."relationships" add constraint "Relationships_pkey" PRIMARY KEY using index "Relationships_pkey";

alter table "public"."ticket_types" add constraint "ticket_types_pkey" PRIMARY KEY using index "ticket_types_pkey";

alter table "public"."tickets" add constraint "tickets_pkey" PRIMARY KEY using index "tickets_pkey";

alter table "public"."performances" add constraint "performances_pkey" PRIMARY KEY using index "performances_pkey";

alter table "public"."performances" add constraint "performances_class_id_key" UNIQUE using index "performances_class_id_key";

alter table "public"."performances" add constraint "performances_class_name_key" UNIQUE using index "performances_class_name_key";

alter table "public"."performances_schedule" add constraint "performances_schedule_round_number_key" UNIQUE using index "performances_schedule_round_number_key";

alter table "public"."ticket_types" add constraint "ticket_types_name_key" UNIQUE using index "ticket_types_name_key";

alter table "public"."tickets" add constraint "tickets_code_key" UNIQUE using index "tickets_code_key";

alter table "public"."tickets" add constraint "tickets_performance_id_fkey" FOREIGN KEY (performance_id) REFERENCES public.performances(class_id) not valid;

alter table "public"."tickets" validate constraint "tickets_performance_id_fkey";

alter table "public"."tickets" add constraint "tickets_relationship_fkey" FOREIGN KEY (relationship) REFERENCES public.relationships(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tickets" validate constraint "tickets_relationship_fkey";

alter table "public"."tickets" add constraint "tickets_round_number_fkey" FOREIGN KEY (round_number) REFERENCES public.performances_schedule(round_number) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tickets" validate constraint "tickets_round_number_fkey";

alter table "public"."tickets" add constraint "tickets_ticket_type_fkey" FOREIGN KEY (ticket_type) REFERENCES public.ticket_types(name) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tickets" validate constraint "tickets_ticket_type_fkey";

alter table "public"."tickets" add constraint "tickets_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tickets" validate constraint "tickets_user_id_fkey";

grant delete on table "public"."performances" to "postgres";

grant insert on table "public"."performances" to "postgres";

grant references on table "public"."performances" to "postgres";

grant select on table "public"."performances" to "postgres";

grant trigger on table "public"."performances" to "postgres";

grant truncate on table "public"."performances" to "postgres";

grant update on table "public"."performances" to "postgres";

grant delete on table "public"."performances_schedule" to "anon";

grant insert on table "public"."performances_schedule" to "anon";

grant references on table "public"."performances_schedule" to "anon";

grant select on table "public"."performances_schedule" to "anon";

grant trigger on table "public"."performances_schedule" to "anon";

grant truncate on table "public"."performances_schedule" to "anon";

grant update on table "public"."performances_schedule" to "anon";

grant delete on table "public"."performances_schedule" to "authenticated";

grant insert on table "public"."performances_schedule" to "authenticated";

grant references on table "public"."performances_schedule" to "authenticated";

grant select on table "public"."performances_schedule" to "authenticated";

grant trigger on table "public"."performances_schedule" to "authenticated";

grant truncate on table "public"."performances_schedule" to "authenticated";

grant update on table "public"."performances_schedule" to "authenticated";

grant delete on table "public"."performances_schedule" to "postgres";

grant insert on table "public"."performances_schedule" to "postgres";

grant references on table "public"."performances_schedule" to "postgres";

grant select on table "public"."performances_schedule" to "postgres";

grant trigger on table "public"."performances_schedule" to "postgres";

grant truncate on table "public"."performances_schedule" to "postgres";

grant update on table "public"."performances_schedule" to "postgres";

grant delete on table "public"."performances_schedule" to "service_role";

grant insert on table "public"."performances_schedule" to "service_role";

grant references on table "public"."performances_schedule" to "service_role";

grant select on table "public"."performances_schedule" to "service_role";

grant trigger on table "public"."performances_schedule" to "service_role";

grant truncate on table "public"."performances_schedule" to "service_role";

grant update on table "public"."performances_schedule" to "service_role";

grant delete on table "public"."relationships" to "anon";

grant insert on table "public"."relationships" to "anon";

grant references on table "public"."relationships" to "anon";

grant select on table "public"."relationships" to "anon";

grant trigger on table "public"."relationships" to "anon";

grant truncate on table "public"."relationships" to "anon";

grant update on table "public"."relationships" to "anon";

grant delete on table "public"."relationships" to "authenticated";

grant insert on table "public"."relationships" to "authenticated";

grant references on table "public"."relationships" to "authenticated";

grant select on table "public"."relationships" to "authenticated";

grant trigger on table "public"."relationships" to "authenticated";

grant truncate on table "public"."relationships" to "authenticated";

grant update on table "public"."relationships" to "authenticated";

grant delete on table "public"."relationships" to "postgres";

grant insert on table "public"."relationships" to "postgres";

grant references on table "public"."relationships" to "postgres";

grant select on table "public"."relationships" to "postgres";

grant trigger on table "public"."relationships" to "postgres";

grant truncate on table "public"."relationships" to "postgres";

grant update on table "public"."relationships" to "postgres";

grant delete on table "public"."relationships" to "service_role";

grant insert on table "public"."relationships" to "service_role";

grant references on table "public"."relationships" to "service_role";

grant select on table "public"."relationships" to "service_role";

grant trigger on table "public"."relationships" to "service_role";

grant truncate on table "public"."relationships" to "service_role";

grant update on table "public"."relationships" to "service_role";

grant delete on table "public"."ticket_types" to "anon";

grant insert on table "public"."ticket_types" to "anon";

grant references on table "public"."ticket_types" to "anon";

grant select on table "public"."ticket_types" to "anon";

grant trigger on table "public"."ticket_types" to "anon";

grant truncate on table "public"."ticket_types" to "anon";

grant update on table "public"."ticket_types" to "anon";

grant delete on table "public"."ticket_types" to "authenticated";

grant insert on table "public"."ticket_types" to "authenticated";

grant references on table "public"."ticket_types" to "authenticated";

grant select on table "public"."ticket_types" to "authenticated";

grant trigger on table "public"."ticket_types" to "authenticated";

grant truncate on table "public"."ticket_types" to "authenticated";

grant update on table "public"."ticket_types" to "authenticated";

grant delete on table "public"."ticket_types" to "postgres";

grant insert on table "public"."ticket_types" to "postgres";

grant references on table "public"."ticket_types" to "postgres";

grant select on table "public"."ticket_types" to "postgres";

grant trigger on table "public"."ticket_types" to "postgres";

grant truncate on table "public"."ticket_types" to "postgres";

grant update on table "public"."ticket_types" to "postgres";

grant delete on table "public"."ticket_types" to "service_role";

grant insert on table "public"."ticket_types" to "service_role";

grant references on table "public"."ticket_types" to "service_role";

grant select on table "public"."ticket_types" to "service_role";

grant trigger on table "public"."ticket_types" to "service_role";

grant truncate on table "public"."ticket_types" to "service_role";

grant update on table "public"."ticket_types" to "service_role";

grant delete on table "public"."tickets" to "anon";

grant insert on table "public"."tickets" to "anon";

grant references on table "public"."tickets" to "anon";

grant select on table "public"."tickets" to "anon";

grant trigger on table "public"."tickets" to "anon";

grant truncate on table "public"."tickets" to "anon";

grant update on table "public"."tickets" to "anon";

grant delete on table "public"."tickets" to "authenticated";

grant insert on table "public"."tickets" to "authenticated";

grant references on table "public"."tickets" to "authenticated";

grant select on table "public"."tickets" to "authenticated";

grant trigger on table "public"."tickets" to "authenticated";

grant truncate on table "public"."tickets" to "authenticated";

grant update on table "public"."tickets" to "authenticated";

grant delete on table "public"."tickets" to "postgres";

grant insert on table "public"."tickets" to "postgres";

grant references on table "public"."tickets" to "postgres";

grant select on table "public"."tickets" to "postgres";

grant trigger on table "public"."tickets" to "postgres";

grant truncate on table "public"."tickets" to "postgres";

grant update on table "public"."tickets" to "postgres";

grant delete on table "public"."tickets" to "service_role";

grant insert on table "public"."tickets" to "service_role";

grant references on table "public"."tickets" to "service_role";

grant select on table "public"."tickets" to "service_role";

grant trigger on table "public"."tickets" to "service_role";

grant truncate on table "public"."tickets" to "service_role";

grant update on table "public"."tickets" to "service_role";


  create policy "Enable read access for all users"
  on "public"."performances_schedule"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."relationships"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."ticket_types"
  as permissive
  for select
  to public
using (true);



  create policy "Enable users to view their own data only"
  on "public"."tickets"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



