create type "public"."rehearsal_type" as enum ('official', 'unofficial');

create type "public"."ticket_status" as enum ('valid', 'cancelled', 'used');

alter table "public"."tickets" drop constraint if exists "tickets_performance_id_fkey";

alter table "public"."tickets" drop constraint if exists "tickets_round_number_fkey";

alter table "public"."tickets" drop constraint if exists "tickets_ticket_type_fkey";

alter table "public"."performances" drop constraint if exists "performances_class_id_key";

alter table "public"."performances_schedule" drop constraint if exists "performances_schedule_round_number_key";

do $$
begin
  if to_regclass('public.performances_class_id_key') is not null then
    execute 'drop index "public"."performances_class_id_key"';
  end if;
end
$$;

do $$
begin
  if to_regclass('public.performances_schedule_round_number_key') is not null then
    execute 'drop index "public"."performances_schedule_round_number_key"';
  end if;
end
$$;


  create table "public"."rehearsals" (
    "id" smallint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "class_id" smallint not null,
    "round_id" smallint,
    "round_name" text not null,
    "start_time" timestamp with time zone,
    "is_active" boolean not null default true,
    "type" public.rehearsal_type not null default 'official'::public.rehearsal_type
      );


alter table "public"."rehearsals" enable row level security;

alter table "public"."configs" drop column "shows_per_day";

alter table "public"."configs" add column "junior_release_open" boolean not null default false;

alter table "public"."configs" add column "max_tickets_per_user" smallint not null default '20'::smallint;

alter table "public"."performances" drop column "class_id";

alter table "public"."performances" drop column "junior_remaining";

alter table "public"."performances" drop column "total_remaining";

alter table "public"."performances_schedule" drop column "date_name";

alter table "public"."performances_schedule" drop column "round_number";

alter table "public"."performances_schedule" add column "is_active" boolean not null default true;

alter table "public"."performances_schedule" add column "round_name" text not null;

alter table "public"."teachers" drop column "classId";

alter table "public"."teachers" add column "class_id" smallint;

alter table "public"."tickets" alter column "status" set default 'valid'::public.ticket_status;

alter table "public"."tickets" alter column "status" set data type public.ticket_status using "status"::public.ticket_status;

alter table "public"."tickets" alter column "ticket_type" set data type smallint using "ticket_type"::smallint;

CREATE UNIQUE INDEX rehearsals_pkey ON public.rehearsals USING btree (id);

alter table "public"."rehearsals" add constraint "rehearsals_pkey" PRIMARY KEY using index "rehearsals_pkey";

alter table "public"."rehearsals" add constraint "rehearsals_class_id_fkey" FOREIGN KEY (class_id) REFERENCES public.performances(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."rehearsals" validate constraint "rehearsals_class_id_fkey";

alter table "public"."tickets" add constraint "tickets_performance_id_fkey" FOREIGN KEY (performance_id) REFERENCES public.performances(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tickets" validate constraint "tickets_performance_id_fkey";

alter table "public"."tickets" add constraint "tickets_round_number_fkey" FOREIGN KEY (round_number) REFERENCES public.performances_schedule(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tickets" validate constraint "tickets_round_number_fkey";

alter table "public"."tickets" add constraint "tickets_ticket_type_fkey" FOREIGN KEY (ticket_type) REFERENCES public.ticket_types(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tickets" validate constraint "tickets_ticket_type_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_remaining_seats(p_performance_id smallint, p_schedule_id smallint)
 RETURNS TABLE(remaining_general integer, remaining_junior integer)
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$declare
  total_cap int;
  junior_cap int;
  general_count int;
  junior_count int;
  is_released boolean;
begin
  -- ① 定員取得
  select total_capacity, junior_capacity
  into total_cap, junior_cap
  from performances
  where id = p_performance_id;

  -- ② 解放フラグ取得
  select junior_release_open
  into is_released
  from configs
  limit 1;

  -- ③ 現在の発券枚数を集計
  select
    count(*) filter (where ticket_type in (1, 3) and status='valid'),
    count(*) filter (where ticket_type = 2 and status='valid')
  into general_count, junior_count
  from tickets
  where performance_id = p_performance_id
    and round_number = p_schedule_id;

  -- ④ 解放状態で計算方法を分岐
  if is_released then
    return query
    select
      total_cap - general_count - junior_count,
      0;
  else
    return query
    select
      (total_cap - junior_cap) - general_count,
      junior_cap - junior_count;
  end if;
end;$function$
;

CREATE OR REPLACE FUNCTION public.register_student(student_name text, grade_no integer, class_no integer, student_no integer, teacher_name_input text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$declare
  correct_teacher_name text;
  normalized_input text;
  normalized_correct text;
begin
  -- 1. 担任名を取得
  select name into correct_teacher_name
  from teachers
  where grade = grade_no and "class_id" = class_no;

  if correct_teacher_name is null then
    raise exception '担任情報が見つかりません';
  end if;

  -- 2. 名前を正規化して比較 (スペース削除、異体字対応など)
  normalized_input := replace(replace(replace(teacher_name_input, ' ', ''), '　', ''), '崎', '﨑');
  normalized_correct := replace(replace(replace(correct_teacher_name, ' ', ''), '　', ''), '崎', '﨑');

  if normalized_input != normalized_correct then
    raise exception '担任の先生の名前が一致しません';
  end if;

  -- 3. ユーザー登録
  insert into users (id, email, name, affiliation, role)
  values (
    auth.uid(),
    (select email from auth.users where id = auth.uid()),
    student_name,
    (grade_no * 1000 + class_no * 100 + student_no),
    'student'
  );
end;$function$
;

grant delete on table "public"."rehearsals" to "anon";

grant insert on table "public"."rehearsals" to "anon";

grant references on table "public"."rehearsals" to "anon";

grant select on table "public"."rehearsals" to "anon";

grant trigger on table "public"."rehearsals" to "anon";

grant truncate on table "public"."rehearsals" to "anon";

grant update on table "public"."rehearsals" to "anon";

grant delete on table "public"."rehearsals" to "authenticated";

grant insert on table "public"."rehearsals" to "authenticated";

grant references on table "public"."rehearsals" to "authenticated";

grant select on table "public"."rehearsals" to "authenticated";

grant trigger on table "public"."rehearsals" to "authenticated";

grant truncate on table "public"."rehearsals" to "authenticated";

grant update on table "public"."rehearsals" to "authenticated";

grant delete on table "public"."rehearsals" to "postgres";

grant insert on table "public"."rehearsals" to "postgres";

grant references on table "public"."rehearsals" to "postgres";

grant select on table "public"."rehearsals" to "postgres";

grant trigger on table "public"."rehearsals" to "postgres";

grant truncate on table "public"."rehearsals" to "postgres";

grant update on table "public"."rehearsals" to "postgres";

grant delete on table "public"."rehearsals" to "service_role";

grant insert on table "public"."rehearsals" to "service_role";

grant references on table "public"."rehearsals" to "service_role";

grant select on table "public"."rehearsals" to "service_role";

grant trigger on table "public"."rehearsals" to "service_role";

grant truncate on table "public"."rehearsals" to "service_role";

grant update on table "public"."rehearsals" to "service_role";
